extends: default

rules:
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: false
  line-length: disable
  comments-indentation: disable
  document-start: disable
  new-line-at-end-of-file: enable
  trailing-spaces: enable
