global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: production

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_cpu_.*'
        action: keep
      - source_labels: [__name__]
        regex: 'node_memory_.*'
        action: keep
      - source_labels: [__name__]
        regex: 'node_disk_.*'
        action: keep
      - source_labels: [__name__]
        regex: 'node_network_.*'
        action: keep

  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'materialize'
    static_configs:
      - targets: ['materialize:6875']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'questdb'
    static_configs:
      - targets: ['questdb:9003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: '/metrics'
    scrape_interval: 10s
    params:
      format: ['prometheus']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
    basic_auth:
      username: metrics
      password: metrics-password
    metrics_path: '/metrics'
    scrape_interval: 10s 