# Configuration for prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'questdb'
    static_configs:
      - targets: ['questdb:9000']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'dagster'
    static_configs:
      - targets: ['dagster:3000']
