# Configuration for dagster.yaml

scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher
  config:
    env_vars:
      - DAGSTER_HOME
      - DAGSTER_POSTGRES_HOST
      - DAGSTER_POSTGRES_PORT
      - DAGSTER_POSTGRES_USER
      - DAGSTER_POSTGRES_PASSWORD
      - DAGSTER_POSTGRES_DB
      - DAGSTER_QUESTDB_HOST
      - DAGSTER_QUESTDB_PORT
      - DAGSTER_CLICKHOUSE_HOST
      - DAGSTER_CLICKHOUSE_PORT

storage:
  postgres:
    postgres_db:
      hostname: ${DAGSTER_POSTGRES_HOST}
      username: ${DAGSTER_POSTGRES_USER}
      password: ${DAGSTER_POSTGRES_PASSWORD}
      db_name: ${DAGSTER_POSTGRES_DB}
      port: ${DAGSTER_POSTGRES_PORT}

compute_logs:
  module: dagster.core.storage.compute_log_manager
  class: ComputeLogManager
  config:
    base_dir: /var/log/dagster
