version: 1
disable_existing_loggers: false

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: /var/log/api/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: /var/log/api/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
    level: ERROR

loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: false

  uvicorn.error:
    handlers: [error_file]
    level: ERROR
    propagate: false

  uvicorn.access:
    handlers: [file]
    level: INFO
    propagate: false

  fastapi:
    handlers: [console, file]
    level: INFO
    propagate: false

  app:
    handlers: [console, file, error_file]
    level: INFO
    propagate: false

root:
  handlers: [console, file, error_file]
  level: INFO 