global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web
          scheme: http
  traefik:
    address: ":8080"
  metrics:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: thedata_net

log:
  level: DEBUG
  format: json

accessLog:
  format: json
  filePath: "/var/log/traefik/access.log"

metrics:
  prometheus:
    entryPoint: metrics

pilot:
  dashboard: false

traefik:
  address: ":8083"
  metrics:
    address: ":8082" 